# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfb620407089d738b69fbd4a9884071a41371fcf668cec2684f9c7d2bd8738a25e40d19795dd3a56ab08fd306a1acf31e0f3950bcd96f5c0a743823e85550093

test:
  secret_key_base: 1303ec9b5a51703c5e8b13eed2d664a0c60bf8fafad617e26617df697940404696fb4891baac8d3055496ac689cc639da15538dd552560b736704db869584a9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
